### ISSUE TITLE
[Capstone Project] Kanban board setup

### ISSUE THREAD

**Issue by jaflih** [jaflih/catalog_of_my_things#31]
Link to the kanban : www.github.com/jaflih/catalog_of_my_things/projects/1

**How many people there are in your team ?**
We are 3

Team member: @Ginohmk 
Team member @Debas-31 
Team member @jaflih

**Comment by MahmoudBakr23** [comment]
Hi team 😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jaflih** [comment]
Hi @MahmoudBakr23 
![thanks](https://user-images.githubusercontent.com/7243132/163861741-93ffbe6c-0da9-4a98-8809-59305baa0775.jpeg)
